### ISSUE TITLE
Issue 3: Map_Graphics class has a lot of redundant code

### ISSUE THREAD

**Issue by JAndrei209** [JAndrei209/COMP-55-Resurrection-Pt-1#3]
Condition statements and for loops in the Map_Graphics class have a lot repeating code
Steps:
create a new class for condition statements that iterate through an array of choices instead of pasting the same text over and over again.
delete any repeating code, and add new classes that have a specific function.

**Comment by onzfonz** [comment]
This is the one that seems the best, but I would like you to make it so that the maps are more general, like you could maybe have sand or water or ice in a file and then it would end up loading those graphics.
Thinking of it that way would help with the redundancy.
Please think about how to generalize the class so much so that someone else without programming experience could make changes to the program
